version: '2'
services:
  magicmirror:
    container_name: magicmirror
    image: mymagicmirror:1.0
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pkolar/projects/private/docker/docker-magicmirror/config:/opt/magic_mirror/config
      - /home/pkolar/projects/private/docker/docker-magicmirror/css/custom.css:/opt/magic_mirror/css/custom.css
    ports:
      - 8888:8080